#
TARGETING_HERO = "Maliken"
HERO_SELECTION_LIST = [
    "Accursed"            
    "Aluna"               
    "Amun-Ra"             
    "Andromeda"           
    "Arachna"             
    "Armadon"             
    "Behemoth"            
    "Blacksmith"          
    "Blood_Hunter"        
    "Bombardier"          
    "Bubbles"             
    "Chronos"             
    "Corrupted Disciple"  
    "Deadwood"            
    "Defiler"             
    "Demented Shaman"     
    "Devourer"            
    "Doctor Repulsor"     
    "Drunken Master"      
    "Electrician"         
    "Ellonia"             
    "Empath"              
    "Engineer"            
    "Fayde"               
    "Flint_Beastwood"     
    "Flux"                
    "Forsaken Archer"     
    "Gauntlet"            
    "Gemini"              
    "Geomancer"           
    "Glacius"             
    "Gunblade"            
    "Hammerstorm"         
    "Hellbringer"         
    "Jeraziah"            
    "Keeper_of_the_Forest"
    "King Klout"          
    "Kraken"              
    "Legionnaire"         
    "Lodestone"           
    "Magebane"            
    "Magmus"              
    "Maliken"             
    "Martyr"              
    "Midas"               
    "Monarch"             
    "Monkey_King"         
    "Moonqueen"           
    "Moraxus"             
    "Myrmidon"            
    "Night_Hound"         
    "Nomad"               
    "Nymphora"            
    "Ophelia"             
    "Pandamonium"         
    "Pearl"               
    "Pebbles"             
    "Pestilence"          
    "Pharoah"             
    "Plague_Rider"        
    "Pollywog_Priest"     
    "Predator"            
    "Prophet"             
    "Puppet_Master"       
    "Pyromancer"          
    "Rampage"             
    "Rhapsody"            
    "Riftwalker"          
    "Sandwraith"          
    "Scout"               
    "Silhouette"          
    "Sir_Benzington"      
    "Slither"             
    "Solstice"            
    "Soul_Reaper"         
    "Soulstealer"         
    "Swiftblade"          
    "Tempest"             
    "The_Gladiator"       
    "The_Chipper"         
    "The_Madman"          
    "Thunderbringer"      
    "Torturer"            
    "Tundra"              
    "Valkyrie"            
    "Vindicator"          
    "Voodoo_Jester"       
    "Warbeast"            
    "Witch Slayer"        
    "Wretched_Hag"        
    "Zephyr"              
]